Update circle.yml

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -30,11 +30,34 @@ jobs:
       - run:
           name: run tests
           command: |
-            go test \
-              -exec testrunner \
-              -covermode=count \
-              -coverprofile=coverage_tmp.txt \
-              github.com/turbinelabs/$PROJECT/...
+            function die() {
+              echo $*
+              exit 1
+            }
+
+            # Initialize error tracking
+            ERROR=""
+
+            rm -rf coverage.txt
+            touch coverage.txt
+
+            # Test each package and append coverage profile info to coverage.txt
+            for PKG in $(go list $PKG/... | grep -v /vendor/); do
+                go test $GO_TEST_RUNNER \
+                  -timeout $GO_TEST_TIMEOUT \
+                  -covermode=count \
+                  -coverprofile=coverage_tmp.txt \
+                  $PKG || ERROR="$ERROR $PKG"
+
+                cat coverage_tmp.txt  | grep -v "/mock_" >> coverage.txt
+            done
+
+            rm -rf coverage_tmp.txt
+
+            if [ ! -z "$ERROR" ]
+            then
+                die "Encountered error for one or more packages: $ERROR"
+            fi
               
       - run: bash <(curl -s https://codecov.io/bash)
 
